use std::default::Default;
use std::fmt;
use std::str::FromStr;
use std::vec::Vec;

use failure;

use pm_lib::index::Dependencies;
use pm_lib::package::PackageName;
use pm_lib::version::Version;

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Lockfile {
    pub meta: LockfileMeta,
    pub locked_dependencies: Vec<LockedDependency>,
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq)]
pub struct LockfileMeta {
    install: String,
    update: String,
}

impl Default for LockfileMeta {
    fn default() -> Self {
        LockfileMeta {
            install: "1.0".to_string(),
            update: "1.0".to_string(),
        }
    }
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq)]
pub struct LockedDependency {
    pub package_name: PackageName,
    pub version: Version,
    pub dependencies: Dependencies,
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq)]
pub enum LockfileEntry {
    #[serde(rename = "package_manager")]
    Meta(LockfileMeta),
    #[serde(rename = "dependency")]
    Dependency(LockedDependency),
}

#[derive(Serialize, Debug, Clone, PartialEq, Eq)]
pub enum LockfileEntryGuard<'a> {
    #[serde(rename = "package_manager")]
    Meta {},
    #[serde(rename = "dependency")]
    Dependency { package_name: &'a PackageName },
}

impl LockfileEntry {
    pub fn guard(&self) -> LockfileEntryGuard {
        match self {
            LockfileEntry::Meta(_) => LockfileEntryGuard::Meta {},
            LockfileEntry::Dependency(locked_dependency) => LockfileEntryGuard::Dependency {
                package_name: &locked_dependency.package_name,
            },
        }
    }
}

impl fmt::Display for Lockfile {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        fn write_entry(f: &mut fmt::Formatter<'_>, lockfile_entry: &LockfileEntry) -> fmt::Result {
            let entry_string = ::serde_json::to_string(&lockfile_entry).unwrap();
            let guard_string = ::serde_json::to_string(&lockfile_entry.guard()).unwrap();
            writeln!(f, "### {}", guard_string)?;
            writeln!(f, "    {}", entry_string)?;
            writeln!(f, "  # {}", guard_string)?;
            Ok(())
        }

        writeln!(
            f,
            "### THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY."
        )?;

        let meta = LockfileEntry::Meta(self.meta.clone());
        write_entry(f, &meta)?;

        for locked_dependency in &self.locked_dependencies {
            let dependency_entry = LockfileEntry::Dependency(locked_dependency.clone());
            write_entry(f, &dependency_entry)?;
        }
        Ok(())
    }
}

impl FromStr for Lockfile {
    type Err = failure::Error;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        let mut maybe_meta: Option<LockfileMeta> = None;
        let mut dependencies: Vec<LockedDependency> = vec![];
        for line in s.lines() {
            let line = line.trim_start_matches(" ");
            if line.is_empty() || line.starts_with("#") {
                continue;
            }
            let entry = ::serde_json::from_str::<LockfileEntry>(line)?;
            match entry {
                LockfileEntry::Meta(m) => {
                    if maybe_meta.is_some() {
                        bail!("duplicate meta entry");
                    }
                    if !dependencies.is_empty() {
                        bail!("meta entry must come before dependencies");
                    }
                    if m.install != "1.0" {
                        bail!("package_manager version {} is required to install dependencies")
                    }
                    maybe_meta = Some(m);
                }
                LockfileEntry::Dependency(d) => {
                    if maybe_meta.is_none() {
                        bail!("missing meta entry");
                    }
                    dependencies.push(d);
                }
            }
        }
        let meta = match maybe_meta {
            // Allow empty lockfiles
            None => LockfileMeta::default(),
            Some(m) => m,
        };
        Ok(Lockfile {
            meta,
            locked_dependencies: dependencies,
        })
    }
}

#[cfg(test)]
mod test {
    use super::*;
    use pm_lib::test_helpers::*;

    #[test]
    fn roundtrip() {
        let lockfile = Lockfile {
            meta: LockfileMeta::default(),
            locked_dependencies: vec![LockedDependency {
                package_name: pkg("x"),
                version: ver("1.0.0"),
                dependencies: Dependencies::new(),
            }],
        };
        let serialized = lockfile.to_string();
        assert_eq!(Lockfile::from_str(&serialized).unwrap(), lockfile);
    }
}
